// svelte-test/src/components/TwoPaneManager.svelte
<script>
  import { getDisplayName, formatFileSize } from '../models.js';
  import { HardDrive, Archive, Save, X } from 'lucide-svelte';

  export let title = 'Models';
  export let macModels = [];
  export let stashModels = [];

  let selectedModel = null;
  let showModal = false;

  function handleModelClick(model) {
    selectedModel = model;
    showModal = true;
  }

  function closeModal() {
    showModal = false;
    selectedModel = null;
  }
</script>

<div class="container">
  <!-- Header -->
  <div class="header">
    <h1>{title}</h1>
    <div class="header-actions">
      <button class="btn-secondary" disabled>
        <X size={18} />
        Cancel
      </button>
      <button class="btn-primary" disabled>
        <Save size={18} />
        Save Changes
      </button>
    </div>
  </div>

  <!-- Two Pane Layout -->
  <div class="content">
    <!-- Mac HD Pane -->
    <div class="pane">
      <div class="pane-header">
        <HardDrive size={16} />
        <h2>Macintosh HD</h2>
        <span class="pane-count">{macModels.length}</span>
      </div>
      <div class="pane-content">
        {#each macModels as model, index (model.filename)}
          <div
            class="model-item"
            on:click={() => handleModelClick(model)}
            role="button"
            tabindex="0"
          >
            <div class="model-order">{index + 1}</div>
            <div class="model-info">
              <div class="model-name">{getDisplayName(model)}</div>
              <div class="model-details">
                <span class="model-size">{formatFileSize(model.file_size)}</span>
                {#if model.lora_strength}
                  <span class="lora-strength">Strength: {(model.lora_strength / 10).toFixed(1)}</span>
                {/if}
              </div>
            </div>
          </div>
        {:else}
          <div class="empty-state">
            <p>No models on Mac HD</p>
            <p class="empty-hint">Drag models from Stash to add them</p>
          </div>
        {/each}
      </div>
    </div>

    <!-- Stash Pane -->
    <div class="pane">
      <div class="pane-header">
        <Archive size={16} />
        <h2>Stash</h2>
        <span class="pane-count">{stashModels.length}</span>
      </div>
      <div class="pane-content">
        {#each stashModels as model (model.filename)}
          <div
            class="model-item"
            on:click={() => handleModelClick(model)}
            role="button"
            tabindex="0"
          >
            <div class="model-info full-width">
              <div class="model-name">{getDisplayName(model)}</div>
              <div class="model-details">
                <span class="model-size">{formatFileSize(model.file_size)}</span>
                {#if model.lora_strength}
                  <span class="lora-strength">Strength: {(model.lora_strength / 10).toFixed(1)}</span>
                {/if}
              </div>
            </div>
          </div>
        {:else}
          <div class="empty-state">
            <p>No models in stash</p>
            <p class="empty-hint">Models removed from Mac HD will appear here</p>
          </div>
        {/each}
      </div>
    </div>
  </div>

  <!-- Modal -->
  {#if showModal && selectedModel}
    <div class="modal-overlay" on:click={closeModal} role="presentation">
      <div class="modal" on:click|stopPropagation role="dialog">
        <div class="modal-header">
          <h3>Model Details</h3>
          <button class="modal-close" on:click={closeModal}>✕</button>
        </div>
        <div class="modal-content">
          <div class="detail-row">
            <span class="detail-label">Filename:</span>
            <span class="detail-value">{selectedModel.filename}</span>
          </div>
          <div class="detail-row">
            <span class="detail-label">Display Name:</span>
            <span class="detail-value">{getDisplayName(selectedModel)}</span>
          </div>
          <div class="detail-row">
            <span class="detail-label">File Size:</span>
            <span class="detail-value">{formatFileSize(selectedModel.file_size)}</span>
          </div>
          <div class="detail-row">
            <span class="detail-label">On Mac HD:</span>
            <span class="detail-value">{selectedModel.exists_mac_hd ? 'Yes' : 'No'}</span>
          </div>
          <div class="detail-row">
            <span class="detail-label">In Stash:</span>
            <span class="detail-value">{selectedModel.exists_stash ? 'Yes' : 'No'}</span>
          </div>
          {#if selectedModel.lora_strength}
            <div class="detail-row">
              <span class="detail-label">LoRA Strength:</span>
              <span class="detail-value">{(selectedModel.lora_strength / 10).toFixed(1)}</span>
            </div>
          {/if}
        </div>
      </div>
    </div>
  {/if}
</div>

<style>
  .container {
    display: flex;
    flex-direction: column;
    height: 100%;
    width: 100%;
  }

  .header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 12px 32px;
    border-bottom: 1px solid #e5e7eb;
    background: white;
  }

  .header h1 {
    margin: 0;
    font-size: 24px;
    font-weight: 700;
    color: #111827;
  }

  .header-actions {
    display: flex;
    gap: 12px;
  }

  .btn-primary, .btn-secondary {
    display: flex;
    align-items: center;
    gap: 8px;
    padding: 4px 12px;
    border-radius: 6px;
    font-size: 14px;
    font-weight: 600;
    cursor: pointer;
    transition: all 0.2s;
    border: none;
  }

  .btn-primary {
    background: #ff5f57;
    color: white;
    border: none;
  }

  .btn-primary:hover:not(:disabled) {
    background: #ff4842;
  }

  .btn-secondary {
    background: white;
    color: #374151;
    border: 1px solid #e5e7eb;
  }

  .btn-secondary:hover:not(:disabled) {
    background: #f9fafb;
  }

  .btn-primary:disabled, .btn-secondary:disabled {
    opacity: 0.4;
    cursor: not-allowed;
  }

  .content {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 0;
    flex: 1;
    overflow: hidden;
  }

  .pane {
    background: white;
    display: flex;
    flex-direction: column;
    overflow: hidden;
    border-right: 2px solid #e5e7eb;
  }

  .pane:last-child {
    border-right: none;
  }

  .pane-header {
    display: flex;
    align-items: center;
    gap: 12px;
    padding: 6px 24px;
    border-bottom: 1px solid #e5e7eb;
    background: #f3f4f6;
  }

  .pane-header h2 {
    margin: 0;
    font-size: 20px;
    font-weight: 700;
    color: #111827;
    flex: 1;
  }

  .pane-count {
    background: #e5e7eb;
    color: #374151;
    padding: 2px 10px;
    border-radius: 12px;
    font-size: 14px;
    font-weight: 600;
  }

  .pane-content {
    flex: 1;
    overflow-y: auto;
    padding: 16px;
  }

  .model-item {
    display: flex;
    align-items: center;
    gap: 12px;
    padding: 8px 16px;
    margin-bottom: 8px;
    border: 1px solid #e5e7eb;
    border-radius: 6px;
    cursor: pointer;
    transition: all 0.2s;
    background: white;
  }

  .model-item:hover {
    border-color: #ff5f57;
    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
  }

  .model-order {
    width: 28px;
    height: 28px;
    display: flex;
    align-items: center;
    justify-content: center;
    background: #f3f4f6;
    border-radius: 4px;
    font-size: 14px;
    font-weight: 700;
    color: #374151;
    flex-shrink: 0;
  }

  .model-info {
    flex: 1;
    min-width: 0;
  }

  .model-info.full-width {
    width: 100%;
  }

  .model-name {
    font-size: 14px;
    font-weight: 600;
    color: #111827;
    margin-bottom: 4px;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }

  .model-details {
    display: flex;
    gap: 12px;
    font-size: 13px;
    color: #6b7280;
  }

  .lora-strength {
    color: #ff5f57;
    font-weight: 600;
  }

  .empty-state {
    text-align: center;
    padding: 60px 24px;
    color: #6b7280;
  }

  .empty-state p {
    margin: 8px 0;
    font-size: 14px;
  }

  .empty-hint {
    font-size: 14px;
    color: #9ca3af;
  }

  .modal-overlay {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background: rgba(0, 0, 0, 0.5);
    display: flex;
    align-items: center;
    justify-content: center;
    z-index: 1000;
  }

  .modal {
    background: white;
    border-radius: 8px;
    width: 90%;
    max-width: 500px;
    max-height: 90vh;
    overflow: hidden;
    display: flex;
    flex-direction: column;
  }

  .modal-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 20px 24px;
    border-bottom: 1px solid #e5e7eb;
  }

  .modal-header h3 {
    margin: 0;
    font-size: 18px;
    font-weight: 600;
    color: #111827;
  }

  .modal-close {
    background: none;
    border: none;
    font-size: 24px;
    color: #6b7280;
    cursor: pointer;
    padding: 0;
    width: 32px;
    height: 32px;
    display: flex;
    align-items: center;
    justify-content: center;
    border-radius: 4px;
  }

  .modal-close:hover {
    background: #f3f4f6;
  }

  .modal-content {
    padding: 24px;
    overflow-y: auto;
  }

  .detail-row {
    display: flex;
    padding: 12px 0;
    border-bottom: 1px solid #f3f4f6;
  }

  .detail-row:last-child {
    border-bottom: none;
  }

  .detail-label {
    font-weight: 600;
    color: #374151;
    width: 140px;
    flex-shrink: 0;
  }

  .detail-value {
    color: #6b7280;
    word-break: break-all;
  }
</style>

// src/components/TwoPaneManager.jsx
'use client';

import { useState, useEffect } from 'react';
import { useDragAndDrop } from '@formkit/drag-and-drop/react';
import { Save, X, HardDrive, Archive } from 'lucide-react';

export default function TwoPaneManager({ 
  modelType, 
  title,
  macModels = [],
  stashModels = [],
  onReorder,
  onAddToMac,
  onRemoveFromMac,
  onSave,
  onCancel,
  hasUnsavedChanges = false,
  loading = false,
}) {
  const [showModal, setShowModal] = useState(false);
  const [selectedModel, setSelectedModel] = useState(null);

  // Initialize drag and drop for Mac pane
  const [macListRef, macItems, setMacItems] = useDragAndDrop(
    macModels,
    {
      group: 'models',
      onSort: (newOrder) => {
        onReorder(newOrder);
      },
    }
  );

  // Update mac items when prop changes
  useEffect(() => {
    setMacItems(macModels);
  }, [macModels, setMacItems]);

  // Handle model click to show details
  const handleModelClick = (model) => {
    setSelectedModel(model);
    setShowModal(true);
  };

  // Format file size
  const formatFileSize = (bytes) => {
    if (!bytes) return 'Unknown';
    const gb = bytes / (1024 * 1024 * 1024);
    if (gb >= 1) return `${gb.toFixed(2)} GB`;
    const mb = bytes / (1024 * 1024);
    return `${mb.toFixed(2)} MB`;
  };

  // Check if model is in Mac pane
  const isOnMac = (modelId) => {
    return macModels.some(m => m.model.id === modelId);
  };

  return (
    <div className="two-pane-container">
      {/* Header */}
      <div className="header">
        <h1 className="title">{title}</h1>
        <div className="header-actions">
          <button
            className="btn-cancel"
            onClick={onCancel}
            disabled={!hasUnsavedChanges || loading}
          >
            <X size={18} />
            Cancel
          </button>
          <button
            className="btn-save"
            onClick={onSave}
            disabled={!hasUnsavedChanges || loading}
          >
            <Save size={18} />
            {loading ? 'Saving...' : 'Save Changes'}
          </button>
        </div>
      </div>

      {/* Two Panes */}
      <div className="panes">
        {/* Left Pane - Mac HD */}
        <div className="pane pane-mac">
          <div className="pane-header">
            <HardDrive size={20} />
            <h2>Macintosh HD</h2>
            <span className="count">{macModels.length}</span>
          </div>
          <div className="pane-content" ref={macListRef}>
            {macModels.length === 0 ? (
              <div className="empty-state">
                <p>No models on Mac HD</p>
                <p className="hint">Drag models from Stash to add them</p>
              </div>
            ) : (
              macModels.map((item, index) => (
                <div
                  key={item.model.id}
                  className="model-item draggable"
                  onDoubleClick={() => handleModelClick(item)}
                  data-drag-disabled="false"
                >
                  <div className="model-order">{index + 1}</div>
                  <div className="model-info">
                    <div className="model-name">
                      {item.custom_name || item.model.display_name || item.model.filename}
                    </div>
                    <div className="model-meta">
                      {formatFileSize(item.model.file_size)}
                      {item.lora_strength && (
                        <span className="lora-strength">
                          Strength: {item.lora_strength}
                        </span>
                      )}
                    </div>
                  </div>
                  <button
                    className="btn-remove"
                    onClick={(e) => {
                      e.stopPropagation();
                      onRemoveFromMac(item.model.id);
                    }}
                    title="Remove from Mac"
                  >
                    <X size={16} />
                  </button>
                </div>
              ))
            )}
          </div>
        </div>

        {/* Right Pane - Stash */}
        <div className="pane pane-stash">
          <div className="pane-header">
            <Archive size={20} />
            <h2>Stash</h2>
            <span className="count">{stashModels.length}</span>
          </div>
          <div className="pane-content">
            {stashModels.length === 0 ? (
              <div className="empty-state">
                <p>No models in stash</p>
              </div>
            ) : (
              stashModels.map((item) => {
                const onMac = isOnMac(item.model.id);
                return (
                  <div
                    key={item.model.id}
                    className={`model-item ${onMac ? 'grayed' : ''}`}
                    onDoubleClick={() => handleModelClick(item)}
                    onClick={() => {
                      if (!onMac) {
                        onAddToMac(item.model.id);
                      }
                    }}
                  >
                    <div className="model-info">
                      <div className="model-name">
                        {item.model.display_name || item.model.filename}
                      </div>
                      <div className="model-meta">
                        {formatFileSize(item.model.file_size)}
                      </div>
                    </div>
                    {onMac && (
                      <div className="on-mac-badge">On Mac</div>
                    )}
                  </div>
                );
              })
            )}
          </div>
        </div>
      </div>

      {/* Model Details Modal */}
      {showModal && selectedModel && (
        <div className="modal-overlay" onClick={() => setShowModal(false)}>
          <div className="modal-content" onClick={(e) => e.stopPropagation()}>
            <div className="modal-header">
              <h3>Model Details</h3>
              <button onClick={() => setShowModal(false)}>
                <X size={20} />
              </button>
            </div>
            <div className="modal-body">
              <div className="detail-row">
                <span className="detail-label">Filename:</span>
                <span className="detail-value">{selectedModel.model.filename}</span>
              </div>
              <div className="detail-row">
                <span className="detail-label">Type:</span>
                <span className="detail-value">{selectedModel.model.model_type}</span>
              </div>
              <div className="detail-row">
                <span className="detail-label">Size:</span>
                <span className="detail-value">{formatFileSize(selectedModel.model.file_size)}</span>
              </div>
              {selectedModel.model.checksum && (
                <div className="detail-row">
                  <span className="detail-label">Checksum:</span>
                  <span className="detail-value checksum">{selectedModel.model.checksum}</span>
                </div>
              )}
              <div className="detail-row">
                <span className="detail-label">On Mac HD:</span>
                <span className="detail-value">{selectedModel.is_on_mac ? 'Yes' : 'No'}</span>
              </div>
            </div>
          </div>
        </div>
      )}

      <style jsx>{`
        .two-pane-container {
          display: flex;
          flex-direction: column;
          height: 100%;
        }

        .header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          padding: 24px 32px;
          border-bottom: 1px solid #e0e0e0;
          background: white;
        }

        .title {
          margin: 0;
          font-size: 24px;
          font-weight: 600;
        }

        .header-actions {
          display: flex;
          gap: 12px;
        }

        .btn-cancel, .btn-save {
          display: flex;
          align-items: center;
          gap: 8px;
          padding: 10px 20px;
          border: none;
          border-radius: 6px;
          font-size: 14px;
          font-weight: 500;
          cursor: pointer;
          transition: all 0.2s;
        }

        .btn-cancel {
          background: white;
          color: #666;
          border: 1px solid #e0e0e0;
        }

        .btn-cancel:hover:not(:disabled) {
          background: #f5f5f5;
        }

        .btn-cancel:disabled {
          opacity: 0.4;
          cursor: not-allowed;
        }

        .btn-save {
          background: #ff5f57;
          color: white;
        }

        .btn-save:hover:not(:disabled) {
          background: #ff4540;
        }

        .btn-save:disabled {
          opacity: 0.5;
          cursor: not-allowed;
        }

        .panes {
          display: grid;
          grid-template-columns: 1fr 1fr;
          gap: 0;
          flex: 1;
          overflow: hidden;
        }

        .pane {
          display: flex;
          flex-direction: column;
          height: 100%;
          overflow: hidden;
        }

        .pane-mac {
          border-right: 2px solid #e0e0e0;
        }

        .pane-header {
          display: flex;
          align-items: center;
          gap: 12px;
          padding: 20px 24px;
          background: #f5f5f5;
          border-bottom: 1px solid #e0e0e0;
        }

        .pane-header h2 {
          margin: 0;
          font-size: 18px;
          font-weight: 600;
          flex: 1;
        }

        .count {
          background: #e0e0e0;
          padding: 4px 10px;
          border-radius: 12px;
          font-size: 13px;
          font-weight: 500;
          color: #666;
        }

        .pane-content {
          flex: 1;
          overflow-y: auto;
          padding: 16px;
        }

        .empty-state {
          text-align: center;
          padding: 60px 20px;
          color: #999;
        }

        .empty-state p {
          margin: 8px 0;
        }

        .hint {
          font-size: 13px;
          color: #bbb;
        }

        .model-item {
          display: flex;
          align-items: center;
          gap: 12px;
          padding: 12px 16px;
          background: white;
          border: 1px solid #e0e0e0;
          border-radius: 6px;
          margin-bottom: 8px;
          cursor: pointer;
          transition: all 0.2s;
        }

        .model-item:hover {
          border-color: #ff5f57;
          box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
        }

        .model-item.draggable {
          cursor: grab;
        }

        .model-item.draggable:active {
          cursor: grabbing;
        }

        .model-item.grayed {
          opacity: 0.5;
          background: #f9f9f9;
        }

        .model-item.grayed:hover {
          opacity: 0.6;
        }

        .model-order {
          width: 28px;
          height: 28px;
          display: flex;
          align-items: center;
          justify-content: center;
          background: #f0f0f0;
          border-radius: 4px;
          font-size: 13px;
          font-weight: 600;
          color: #666;
        }

        .model-info {
          flex: 1;
        }

        .model-name {
          font-size: 14px;
          font-weight: 500;
          margin-bottom: 4px;
          word-break: break-word;
        }

        .model-meta {
          font-size: 12px;
          color: #666;
          display: flex;
          gap: 12px;
        }

        .lora-strength {
          color: #ff5f57;
          font-weight: 500;
        }

        .on-mac-badge {
          padding: 4px 10px;
          background: #e3f2fd;
          color: #1976d2;
          border-radius: 4px;
          font-size: 12px;
          font-weight: 500;
        }

        .btn-remove {
          background: transparent;
          border: 1px solid #e0e0e0;
          border-radius: 4px;
          padding: 6px;
          cursor: pointer;
          transition: all 0.2s;
          color: #666;
        }

        .btn-remove:hover {
          background: #fee;
          border-color: #f44336;
          color: #f44336;
        }

        .modal-overlay {
          position: fixed;
          top: 0;
          left: 0;
          right: 0;
          bottom: 0;
          background: rgba(0, 0, 0, 0.5);
          display: flex;
          align-items: center;
          justify-content: center;
          z-index: 1000;
        }

        .modal-content {
          background: white;
          border-radius: 8px;
          padding: 24px;
          max-width: 600px;
          width: 90%;
          max-height: 80vh;
          overflow-y: auto;
        }

        .modal-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 20px;
        }

        .modal-header h3 {
          margin: 0;
          font-size: 20px;
          font-weight: 600;
        }

        .modal-header button {
          background: transparent;
          border: none;
          cursor: pointer;
          padding: 4px;
          color: #666;
        }

        .modal-header button:hover {
          color: #333;
        }

        .modal-body {
          display: flex;
          flex-direction: column;
          gap: 16px;
        }

        .detail-row {
          display: grid;
          grid-template-columns: 120px 1fr;
          gap: 16px;
        }

        .detail-label {
          font-weight: 600;
          color: #666;
        }

        .detail-value {
          color: #333;
          word-break: break-all;
        }

        .detail-value.checksum {
          font-family: 'Monaco', 'Courier New', monospace;
          font-size: 11px;
        }
      `}</style>
    </div>
  );
}
